kubectl apply -f .\db-persistent-volume.yaml
kubectl apply -f .\db-persistent-volume-claim.yaml
kubectl apply -f .\db-configmap.yaml
kubectl apply -f .\db-deployment.yaml
kubectl apply -f .\db-service.yaml
kubectl apply -f .\backend-deployment.yaml
kubectl apply -f .\backend-service.yaml
timeout /t 60 /nobreak
::kubectl port-forward deployment/postgresdb 5433:5432
::kubectl port-forward deployment/backend 8081:8080